package dev.chungjungsoo.gptmobile.service

import dev.chungjungsoo.gptmobile.data.model.Conversation
import dev.chungjungsoo.gptmobile.data.model.Message
import dev.chungjungsoo.gptmobile.util.DebugUtils
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.flow

class TitleGenerationService {
    private val TAG = "TitleGenerationService"

    fun generateTitleForConversation(conversation: Conversation, messages: List<Message>): Flow<String> = flow {
        DebugUtils.logDebug("Generating title for conversation ${conversation.id}")

        // Simple title generation logic - in a real implementation this would call an AI model
        val firstMessage = messages.firstOrNull()?.content ?: ""
        val title = if (firstMessage.length > 30) {
            firstMessage.take(30) + "..."
        } else {
            firstMessage
        }

        // Add a prefix to indicate it's auto-generated
        val autoGeneratedTitle = "Auto: $title"
        
        DebugUtils.logDebug("Generated title: $autoGeneratedTitle")
        emit(autoGeneratedTitle)
    }
}