#!/usr/bin/env python3
"""Generate Android icon variants from the editable, reference-traced SVG.

Uses only Python's standard library. --png additionally requires Inkscape.
The SVG intentionally uses only paths and user-space linear/radial gradients,
which map directly to Android VectorDrawable without rasterizing the artwork.
"""

from __future__ import annotations

import argparse
import copy
from pathlib import Path
import subprocess
import tempfile
import xml.etree.ElementTree as ET

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / 'images/brand/app-icon.svg'
DRAWABLE = ROOT / 'app/src/main/res/drawable'
SVG = '{http://www.w3.org/2000/svg}'
ANDROID = 'http://schemas.android.com/apk/res/android'
AAPT = 'http://schemas.android.com/aapt'
ET.register_namespace('android', ANDROID)
ET.register_namespace('aapt', AAPT)


def attr(name: str) -> str:
    return f'{{{ANDROID}}}{name}'


def android_path(source: ET.Element, gradients: dict[str, ET.Element], monochrome: bool = False) -> ET.Element:
    path = ET.Element('path', {attr('pathData'): source.attrib['d'], attr('fillType'): 'evenOdd'})
    fill = '#FFFFFF' if monochrome else source.attrib['fill']
    if not fill.startswith('url('):
        path.set(attr('fillColor'), fill)
        return path
    definition = gradients[fill[5:-1]]
    aapt = ET.SubElement(path, f'{{{AAPT}}}attr', {'name': 'android:fillColor'})
    radial = definition.tag == SVG + 'radialGradient'
    gradient = ET.SubElement(aapt, 'gradient', {attr('type'): 'radial' if radial else 'linear'})
    names = {'cx': 'centerX', 'cy': 'centerY', 'r': 'gradientRadius'} if radial else {
        'x1': 'startX', 'y1': 'startY', 'x2': 'endX', 'y2': 'endY'
    }
    for svg_name, android_name in names.items():
        gradient.set(attr(android_name), definition.attrib[svg_name])
    for stop in definition:
        alpha = round(float(stop.get('stop-opacity', '1')) * 255)
        colour = f'#{alpha:02X}{stop.attrib["stop-color"][1:]}'
        ET.SubElement(gradient, 'item', {attr('offset'): stop.attrib['offset'], attr('color'): colour})
    return path


def vector(paths: list[ET.Element], gradients: dict[str, ET.Element], *, adaptive: bool = False, monochrome: bool = False) -> str:
    size = '108' if adaptive else '36'
    viewport = '108' if adaptive else '1230'
    root = ET.Element('vector', {
        attr('width'): size + 'dp', attr('height'): size + 'dp',
        attr('viewportWidth'): viewport, attr('viewportHeight'): viewport
    })
    # Fit the complete 985 px wide emblem into Android's 66 dp safe circle.
    # Chat instead preserves the exact reference tile's original proportions.
    transform = {'scaleX': '0.063', 'scaleY': '0.063', 'translateX': '5.616', 'translateY': '5.616'} if adaptive else {
        'translateX': '-153', 'translateY': '-153'
    }
    group = ET.SubElement(root, 'group', {attr(k): v for k, v in transform.items()})
    for path in paths:
        group.append(android_path(path, gradients, monochrome))
    ET.indent(root, space='    ')
    return '<?xml version="1.0" encoding="utf-8"?>\n<!-- Generated by scripts/generate_app_icon.py; edit images/brand/app-icon.svg. -->\n' + ET.tostring(root, encoding='unicode') + '\n'


def outputs() -> dict[str, str]:
    source = ET.parse(SOURCE).getroot()
    gradients = {g.attrib['id']: g for g in source.find(SVG + 'defs')}
    background = list(source.find(f"{SVG}g[@id='background']"))
    emblem = list(source.find(f"{SVG}g[@id='emblem']"))
    circle = 'M153,768 A615,615 0,1 0,1383,768 A615,615 0,1 0,153,768 Z'
    circular_background = copy.deepcopy(background)
    square_background = copy.deepcopy(background)
    for path in circular_background:
        path.set('d', circle)
    for path in square_background:
        path.set('d', 'M153,153 H1383 V1383 H153 Z')
    return {
        'ic_app_emblem.xml': vector(emblem, gradients),
        'ic_gpt_mobile.xml': vector(background + emblem, gradients),
        'ic_gpt_mobile_no_padding.xml': vector(circular_background + emblem, gradients),
        'ic_gpt_mobile_foreground.xml': vector(emblem, gradients, adaptive=True),
        'ic_gpt_mobile_monochrome_foreground.xml': vector([emblem[-1]], gradients, adaptive=True, monochrome=True),
        'ic_gpt_mobile_background_layer.xml': vector(square_background, gradients)
    }


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true', help='Fail if Android resources have drifted from the SVG')
    parser.add_argument('--png', action='store_true', help='Also render README/store PNG exports using Inkscape')
    args = parser.parse_args()
    if args.check and args.png:
        parser.error('--check cannot be combined with --png')
    stale = []
    for name, content in outputs().items():
        path = DRAWABLE / name
        if args.check:
            if not path.exists() or path.read_text() != content:
                stale.append(name)
        else:
            path.write_text(content)
    if stale:
        raise SystemExit('Regenerate icon resources: ' + ', '.join(stale))
    if args.png:
        with tempfile.TemporaryDirectory() as temp:
            png = Path(temp) / 'icon.png'
            subprocess.run(['inkscape', str(SOURCE), f'--export-filename={png}', '--export-width=1024'], check=True)
            for target in ['images/logo.png', 'metadata/en-US/images/icon.png']:
                (ROOT / target).write_bytes(png.read_bytes())
    print('Icon resources match the reference SVG.' if args.check else 'Generated icon resources from the reference SVG.')


if __name__ == '__main__':
    main()
